system:
    default:
        image_variations:
            campaign:
                reference: ~
                filters:
                    geometry/scalewidthdownonly: [770]
                    geometry/crop: [770, 390, 0, 0]
            ref_full:
                reference: ~
                filters:
                    geometry/scaleheight: [676]
                    geometry/crop: [1300, 676, 0, 0]
            ref_little:
                reference: ~
                filters:
                    geometry/scalewidth: [600]
                    geometry/crop: [650, 300, 0, 0]
