system:
    default:
        user:
            layout: ComtoCodeWebsiteBundle::pagelayout.html.twig
        location_view:
            full:
                homepage:
                    controller: ComtoCodeWebsiteBundle:Homepage:listSkillsProject
                    template: ComtoCodeWebsiteBundle:full:homepage.html.twig
                    match:
                        Identifier\ContentType: "homepage"
                landingpageSkills:
                    controller: ComtoCodeWebsiteBundle:Landingpage:skills
                    template: ComtoCodeWebsiteBundle:full:landingpage_skills.html.twig
                    match:
                        Identifier\ContentType: "landing_page"
                        Id\Location: 62
                landingpage:
                    template: ComtoCodeWebsiteBundle:full:landingpage.html.twig
                    match:
                        Identifier\ContentType: "landing_page"
            block:
                skills:
                    template: ComtoCodeWebsiteBundle:block:skills.html.twig
                    match:
                        Identifier\ContentType: "skills"
                reference:
                    template: ComtoCodeWebsiteBundle:block:reference.html.twig
                    match:
                        Identifier\ContentType: "reference"
            embed:
                skills:
                    template: ComtoCodeWebsiteBundle:embed:skills.html.twig
                    match:
                        Identifier\ContentType: "skills"
